<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_register_email</name>
   <tag></tag>
   <elementGuidId>f589e7d1-8473-4d09-9d9b-4bb125548052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36496dee-34dc-4dbe-b9f2-8094988b0450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>798165f5-1fb6-422b-8cb6-359942b167c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_email</value>
      <webElementGuid>9498ebc5-f29d-4fe1-8bed-1519753cbab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1ea77ca2-7c30-43da-951f-9b6d2e8ef51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success ivry-input ivry  undefined</value>
      <webElementGuid>cc5b8f53-281c-455d-9102-2ec5c58b5ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>289dc4ed-2ed1-43e8-9f98-8cefa05bf9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_email&quot;)</value>
      <webElementGuid>24959f04-fcdc-4ab0-b534-5faf9e3cbfce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register_email']</value>
      <webElementGuid>44a53d4e-d0bc-488b-845d-15e941396c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register']/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>eaa58bc8-9e44-49aa-917f-5bf8d856c047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>510ed2c3-2b50-438e-aade-6462a1eba084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register_email' and @type = 'email']</value>
      <webElementGuid>8093d593-d17b-416a-9f54-63903864db3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
